### ISSUE TITLE
Failed to setup in local

### ISSUE THREAD

**Issue by yong-asial** [OnsenUI/onsen.io#576]
# (cd dist/v2/OnsenUI/bindings/react && yarn install && yarn gen-docs)
```
➜  onsen.io git:(master) ✗ (cd dist/v2/OnsenUI/bindings/react && yarn install && yarn gen-docs)
cd: no such file or directory: dist/v2/OnsenUI/bindings/react
```

# gulp serve --lang en
```
➜  onsen.io git:(master) ✗ gulp serve --lang en
[21:50:17] Language: --lang=en
[21:50:17] Environment: staging
[21:50:17] Source: './src/documents_en'
[21:50:17] Destination: './out_en'
[21:50:17] Using gulpfile ~/projects/onsenui/onsen.io/gulpfile.js
[21:50:17] Starting 'serve'...
[21:50:17] Starting 'generate'...
[21:50:17] Starting 'less'...
[21:50:18] Finished 'less' after 1.14 s
[21:50:18] Starting 'metalsmith'...
(node:43247) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[21:50:22] Generated into './out_en'
[21:50:22] Finished 'metalsmith' after 4.61 s
[21:50:22] Starting 'blog'...
tags
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2015-12-3, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at configFromString (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at configFromInput (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at prepareConfig (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createFromConfig (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createLocalOrUTC (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createLocal (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at hooks (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at Object.renderBlogDateShort (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.eval (<anonymous>:1:1)
    at Object.eval (<anonymous>:1:1)
    at eval (<anonymous>:1:1)
    at Function.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/eco/lib/index.js:1:1)
    at Object.renderFileContent (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.partial (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.eval (<anonymous>:1:1)
    at Object.eval (<anonymous>:1:1)
    at eval (<anonymous>:1:1)
    at Function.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/eco/lib/index.js:1:1)
    at exports.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:1:1)
    at convert (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/lib/index.js:1:1)
    at /Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1
    at Array.forEach (<anonymous>:null:null)
    at _each (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1)
    at async.each (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1)
    at /Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/lib/index.js:1:1
    at Immediate.next [as _onImmediate] (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:1:1)
    at processImmediate (node:internal/timers:1:1)
    at process.topLevelDomainCallback (node:domain:1:1)
    at process.callbackTrampoline (node:internal/async_hooks:1:1)

[21:50:26] Finished 'blog' after 3.81 s
[21:50:26] Starting 'authors'...
[21:50:26] Finished 'authors' after 253 ms
[21:50:26] Finished 'generate' after 9.82 s
[21:50:26] Starting 'serve'...
[21:50:27] Finished 'serve' after 258 ms
[21:50:27] Finished 'serve' after 10 s
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.11.3:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: out_en
```

# gulp i18n-translate
```
➜  onsen.io git:(master) ✗  gulp i18n-translate
[21:53:53] Language: --lang=ja
[21:53:53] Environment: staging
[21:53:53] Source: './src/documents_ja'
[21:53:53] Destination: './out_ja'
[21:53:53] Using gulpfile ~/projects/onsenui/onsen.io/gulpfile.js
[21:53:53] Starting 'i18n-translate'...
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/appsize.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/appsize.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/architecture.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/architecture.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/build.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/build.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/community.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/community.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/compilation.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/compilation.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/cordova.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/cordova.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/deploy.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/deploy.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/extend.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/extend.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/faq.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/faq.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/features.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/features.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/frameworks.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/frameworks.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/fundamentals.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/fundamentals.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/index.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/index.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/installation.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/installation.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/lifecycle.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/lifecycle.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/monaca.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/monaca.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/theming.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/theming.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/angular1/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/angular1/index.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/angular2/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/angular2/index.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/jquery/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/jquery/index.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/react/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/react/index.html'
[21:53:53] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/vue/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/vue/index.html'
[21:53:53] Finished 'i18n-translate' after 114 ms
```

**Comment by yong-asial** [comment]
```
➜  onsen.io git:(master) ✗ (cd dist/v2/OnsenUI/css-components && yarn install)
cd: no such file or directory: dist/v2/OnsenUI/css-components
```

**Comment by emccorson** [comment]
Just needs the instructions updated. I am working on it.

For the OnsenUI instructions, use what is in the main repo CONTRIBUTING.md.
After that it should just be `gulp generate --lang en` or whichever gulp command you want.

**Comment by emccorson** [comment]
Fixed in 5e0dc1ee.

**Comment by yong-asial** [comment]
@emccorson 

I pulled the latest code and re-setup and still encounter the same error with following command

## gulp generate --lang en
## gulp serve --lang en
```
➜  onsen.io git:(master) ✗ gulp generate --lang en
[23:27:33] Language: --lang=en
[23:27:33] Environment: staging
[23:27:33] Source: './src/documents_en'
[23:27:33] Destination: './out_en'
[23:27:33] Using gulpfile ~/projects/onsenui/onsen.io/gulpfile.js
[23:27:33] Starting 'generate'...
[23:27:33] Starting 'less'...
[23:27:34] Finished 'less' after 749 ms
[23:27:34] Starting 'metalsmith'...
(node:53370) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[23:27:39] Generated into './out_en'
[23:27:39] Finished 'metalsmith' after 5.49 s
[23:27:39] Starting 'blog'...
tags
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2015-12-3, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at configFromString (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at configFromInput (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at prepareConfig (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createFromConfig (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createLocalOrUTC (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at createLocal (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at hooks (/Users/asial/projects/onsenui/onsen.io/node_modules/moment/moment.js:1:1)
    at Object.renderBlogDateShort (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.eval (<anonymous>:1:1)
    at Object.eval (<anonymous>:1:1)
    at eval (<anonymous>:1:1)
    at Function.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/eco/lib/index.js:1:1)
    at Object.renderFileContent (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.partial (/Users/asial/projects/onsenui/onsen.io/modules/helpers.js:1:1)
    at Object.eval (<anonymous>:1:1)
    at Object.eval (<anonymous>:1:1)
    at eval (<anonymous>:1:1)
    at Function.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/eco/lib/index.js:1:1)
    at exports.eco.render (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:1:1)
    at convert (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/lib/index.js:1:1)
    at /Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1
    at Array.forEach (<anonymous>:null:null)
    at _each (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1)
    at async.each (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:1:1)
    at /Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-templates/lib/index.js:1:1
    at Immediate.next [as _onImmediate] (/Users/asial/projects/onsenui/onsen.io/node_modules/metalsmith-branch/node_modules/ware/lib/index.js:1:1)
    at processImmediate (node:internal/timers:1:1)
    at process.topLevelDomainCallback (node:domain:1:1)
    at process.callbackTrampoline (node:internal/async_hooks:1:1)
```

## ➜  onsen.io git:(master) ✗ gulp serve --lang ja
is working fine

##  gulp i18n-extract
```
➜  onsen.io git:(master) ✗ gulp i18n-extract
[23:30:12] Language: --lang=ja
[23:30:12] Environment: staging
[23:30:12] Source: './src/documents_ja'
[23:30:12] Destination: './out_ja'
[23:30:12] Using gulpfile ~/projects/onsenui/onsen.io/gulpfile.js
[23:30:12] Starting 'i18n-extract'...
[23:30:12] Finished 'i18n-extract' after 126 ms
➜  onsen.io git:(master) ✗ gulp i18n-translate
[23:30:19] Language: --lang=ja
[23:30:19] Environment: staging
[23:30:19] Source: './src/documents_ja'
[23:30:19] Destination: './out_ja'
[23:30:19] Using gulpfile ~/projects/onsenui/onsen.io/gulpfile.js
[23:30:19] Starting 'i18n-translate'...
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/appsize.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/appsize.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/architecture.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/architecture.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/build.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/build.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/community.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/community.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/compilation.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/compilation.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/cordova.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/cordova.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/deploy.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/deploy.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/extend.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/extend.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/faq.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/faq.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/features.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/features.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/frameworks.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/frameworks.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/fundamentals.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/fundamentals.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/index.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/index.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/installation.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/installation.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/lifecycle.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/lifecycle.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/monaca.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/monaca.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/theming.po...
ENOENT: no such file or directory, open '/p/gh/OnsenUI/onsen.io/src/documents_en/v2/guide/theming.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/angular1/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/angular1/index.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/angular2/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/angular2/index.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/jquery/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/jquery/index.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/react/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/react/index.html'
[23:30:19] Processing /Users/asial/projects/onsenui/onsen.io/src/i18n/gettext/v2/guide/vue/index.po...
ENOENT: no such file or directory, open '/Users/masahiro/Data/onsen.io/src/documents_en/v2/guide/vue/index.html'
[23:30:19] Finished 'i18n-translate' after 122 ms
```

**Comment by emccorson** [comment]
I have no idea what the `i18n-translate` task is for since I haven't used that, so you may need to ask someone else (maybe Tanaka-san since he seems to have set up). It's not part of the Circle CI build. I guess it's to generate the files for Japanese translations.

The `serve` task does throw an error, but it still works properly even with the error (as far as I can see).

**Comment by yong-asial** [comment]
@emccorson Thank you. I'll investigate this issue.
